### ISSUE TITLE
doesn't work [BUG] 

### ISSUE THREAD

**Issue by loaimbolc** [Naveq-DevTeam/CheatPack#4]
**Describe the bug**

**To Reproduce**

**Expected behavior**
It says it doesn't work 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows XP Communism Edition]
 - Browser [e.g. Google Chrome, Microsoft Edge]
 - Extension version [e.g. 0.0.2]
 - Other extensions [e.g. Windscribe, Nord VPN, Adblock Plus]

**Additional context**

**Comment by nafcioo** [comment]
Are you an idiot????
Can you read what you post?

**Comment by kacperrrooo** [comment]
Congratulations you're a big idiot than misiotes x

**Comment by nafcioo** [comment]
Closing due to the author's idiocy.

**Comment by efindus** [comment]
> 
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Go to '...'
> 
>     2. Click on '....'
> 
>     3. Scroll down to '....'
> 
>     4. See error
> 
> 
> **Expected behavior**
> It says it doesn't work
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
>     * OS: [e.g. Windows XP Communism Edition]
> 
>     * Browser [e.g. Google Chrome, Microsoft Edge]
> 
>     * Extension version [e.g. 0.0.2]
> 
>     * Other extensions [e.g. Windscribe, Nord VPN, Adblock Plus]
> 
> 
> **Additional context**
> Add any other context about the problem here.

welp.. that's a bug report template... but it's supposed to be filled with data about the bug, not copy pasted...
